<#
Give the rebuilt Codex its own CODEX_HOME, so it and the installed Codex
desktop app cannot affect each other.

Why this is needed: both binaries used to read and write the same home
(C:\Users\<you>\.codex). The desktop app is newer, so its SQLite state DB has
migrations the fork does not know; the fork then refuses to start with
"migration 1 was previously applied but has been modified". Sharing a home also
means sharing sessions, logs, plugin caches and the experience store.

What this script writes into the fork home:
  config.toml   a TRIMMED copy: model / provider / token / reasoning effort /
                auth method / [windows] / [model_providers.*] / the project
                trust entries that point at this workspace.
                Deliberately dropped: `notify` (the desktop app's computer-use
                hook), `[plugins.*]` (they reference the desktop app's runtime
                folders) and unrelated [projects.*] entries.
  models.json   copied, with model_catalog_json re-pointed at this copy.

The bearer token is copied verbatim and never printed.

Usage:
  powershell -NoProfile -ExecutionPolicy Bypass -File setup-fork-home.ps1
  ... -Force        regenerate even if the fork home already has a config
#>
param(
    [string]$RealHome = (Join-Path $env:USERPROFILE ".codex"),
    [string]$ForkHome = (Join-Path $env:USERPROFILE ".codex-experience"),
    [string]$Workspace = "D:\experience_codex",
    [switch]$Force
)
$ErrorActionPreference = "Stop"

$sourceConfig = Join-Path $RealHome "config.toml"
$targetConfig = Join-Path $ForkHome "config.toml"
if (-not (Test-Path $sourceConfig)) { throw "no config at $sourceConfig" }

if ((Test-Path $targetConfig) -and -not $Force) {
    Write-Host "fork home already configured: $targetConfig"
    Write-Host "(pass -Force to regenerate from $sourceConfig)"
    exit 0
}

New-Item -ItemType Directory -Path $ForkHome -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $ForkHome "experience") -Force | Out-Null

# ---- carry over only what the fork needs to talk to the model ------------
$topLevelKeys = @(
    'model', 'model_provider', 'model_reasoning_effort', 'preferred_auth_method',
    'forced_login_method', 'approval_policy', 'sandbox_mode', 'model_catalog_json'
)
# Section headers look like [projects.'d:\experience_codex\experience-main'],
# so compare against the plain path with quotes and doubled separators removed.
$workspaceKey = $Workspace.ToLowerInvariant()

$keptTop = @()
$keptSections = @()
$section = $null
$sectionKept = $false
$providerSections = 0
foreach ($line in Get-Content $sourceConfig) {
    if ($line -match '^\s*\[(?<name>[^\]]+)\]\s*$') {
        $section = $Matches['name']
        if ($section -like 'model_providers.*') {
            $sectionKept = $true
            $providerSections++
        }
        elseif ($section -eq 'windows') {
            $sectionKept = $true
        }
        elseif ($section -like 'projects.*') {
            $normalised = $section.ToLowerInvariant().Replace("'", '').Replace('\\', '\')
            $sectionKept = $normalised.Contains($workspaceKey)
        }
        else {
            $sectionKept = $false
        }
        if ($sectionKept) { $keptSections += "[$section]" }
        continue
    }
    if ($null -eq $section) {
        if ($line -match '^\s*(?<key>[A-Za-z_][A-Za-z0-9_-]*)\s*=') {
            if ($topLevelKeys -contains $Matches['key']) { $keptTop += $line.TrimEnd() }
        }
        continue
    }
    if ($sectionKept) { $keptSections += $line.TrimEnd() }
}
if ($providerSections -eq 0) { throw "no [model_providers.*] block found in $sourceConfig" }

# ---- models catalog: copy it so nothing points back at the real home -----
$modelsLine = @($keptTop | Where-Object { $_ -match '^\s*model_catalog_json\s*=' })
$catalogTarget = Join-Path $ForkHome "models.json"
if ($modelsLine.Count -gt 0) {
    $catalogSource = [regex]::Match([string]$modelsLine[0], '"([^"]+)"').Groups[1].Value
    if (Test-Path $catalogSource) {
        Copy-Item -LiteralPath $catalogSource -Destination $catalogTarget -Force
    }
    else {
        Write-Warning "model catalog not found, leaving the catalog unset: $catalogSource"
    }
    $keptTop = $keptTop | Where-Object { $_ -notmatch '^\s*model_catalog_json\s*=' }
    $slashPath = $catalogTarget.Replace('\', '/')
    $keptTop += "model_catalog_json = `"$slashPath`""
}

$header = @(
    "# Generated by setup-fork-home.ps1 - the rebuilt Codex's own home.",
    "# Source: $sourceConfig",
    "# The installed Codex desktop app keeps using $RealHome and is not touched.",
    "# Trimmed on purpose: no notify hook, no plugin/marketplace paths, no",
    "# MCP servers that belong to the desktop app's runtime.",
    ""
)
$body = @()
$body += $keptTop
$body += ''
$body += $keptSections
$text = (($header + $body) -join [Environment]::NewLine) + [Environment]::NewLine
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($targetConfig, $text, $utf8)

# ---- report (never the token) -------------------------------------------
$written = Get-Content $targetConfig -Raw
$tokenCopied = $written -match 'experimental_bearer_token'
$provider = [regex]::Match($written, 'model_provider\s*=\s*"([^"]+)"').Groups[1].Value
$model = [regex]::Match($written, '(?m)^\s*model\s*=\s*"([^"]+)"').Groups[1].Value
Write-Host "fork home     : $ForkHome"
Write-Host "config        : $targetConfig"
Write-Host "model         : $model (provider: $provider)"
Write-Host "bearer token  : $(if ($tokenCopied) { 'copied from the real config' } else { 'NOT FOUND - check the source config' })"
Write-Host "model catalog : $(if (Test-Path $catalogTarget) { $catalogTarget } else { 'not copied (no model_catalog_json)' })"
Write-Host "trusted dirs  : $((@(Select-String -Path $targetConfig -Pattern '^\[projects\.' -AllMatches).Count)) entr(ies) for this workspace"
Write-Host "dropped       : notify, [plugins.*], unrelated [projects.*]"
Write-Host "real home     : $RealHome (untouched)"
